# Base Image
FROM ubuntu:18.04
LABEL mantainer="Xa-Vez <xavez@linux.com>"

# Install Utilities
RUN apt-get update
RUN apt-get install -y tmux vim traceroute 
RUN echo "utils done!"


# Port to Expose
EXPOSE 9876





 
